name: 'setup_node-cache_dep-install_dep'
description: 'Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ⚙️ & Cache dependencies ⚡
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies 🔧
      shell: bash
      run: npm ci
